name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
      
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        badges-directory: badges

    - name: Commit the badge (if changed)
      uses: EndBug/add-and-commit@v9
      if: ${{ github.event_name != 'pull_request' }}
      with:
        default_author: github_actions
        message: 'chore: update JaCoCo coverage badge'
        add: 'badges'
        new_branch: badges
        push: '--force'
